// AUTO-GENERATED — do not edit by hand.
// Source: KNX master data embedded in Knx.Falcon.Sdk (official KNX Association knx_master.xml).
// Regenerate with:  dotnet run --project scripts/generate-dpt-descriptions

export interface DptDescription {
  /** Official DPT name, e.g. "DPT_Switch" */
  n: string;
  en: string;
  de: string;
}

/** Keys: "1" (main type) and "1.001" (subtype). */
export const DPT_DESCRIPTIONS: Record<string, DptDescription> = {
  '1': { n: '1.xxx', en: '1-bit', de: '1-Bit' },
  '1.001': { n: 'DPT_Switch', en: 'switch', de: 'Schalten' },
  '1.002': { n: 'DPT_Bool', en: 'boolean', de: 'Boolesch' },
  '1.003': { n: 'DPT_Enable', en: 'enable', de: 'Freigeben' },
  '1.004': { n: 'DPT_Ramp', en: 'ramp', de: 'Anstieg' },
  '1.005': { n: 'DPT_Alarm', en: 'alarm', de: 'Alarm' },
  '1.006': { n: 'DPT_BinaryValue', en: 'binary value', de: 'Binärer Wert' },
  '1.007': { n: 'DPT_Step', en: 'step', de: 'Schritt' },
  '1.008': { n: 'DPT_UpDown', en: 'up/down', de: 'Auf/Ab' },
  '1.009': { n: 'DPT_OpenClose', en: 'open/close', de: 'Öffnen/Schließen' },
  '1.010': { n: 'DPT_Start', en: 'start/stop', de: 'Start/Stop' },
  '1.011': { n: 'DPT_State', en: 'state', de: 'Status' },
  '1.012': { n: 'DPT_Invert', en: 'invert', de: 'Invertierung' },
  '1.013': { n: 'DPT_DimSendStyle', en: 'dim send style', de: 'Dimmen Sendeart' },
  '1.014': { n: 'DPT_InputSource', en: 'input source', de: 'Eingangstyp' },
  '1.015': { n: 'DPT_Reset', en: 'reset', de: 'Reset' },
  '1.016': { n: 'DPT_Ack', en: 'acknowledge', de: 'Bestätigung' },
  '1.017': { n: 'DPT_Trigger', en: 'trigger', de: 'Auslöser' },
  '1.018': { n: 'DPT_Occupancy', en: 'occupancy', de: 'Belegung' },
  '1.019': { n: 'DPT_Window_Door', en: 'window/door', de: 'Fenster/Tür' },
  '1.021': { n: 'DPT_LogicalFunction', en: 'logical function', de: 'Logikfunktion' },
  '1.022': { n: 'DPT_Scene_AB', en: 'scene', de: 'Szene' },
  '1.023': { n: 'DPT_ShutterBlinds_Mode', en: 'shutter/blinds mode', de: 'Rollladen/Jalousie Modus' },
  '1.024': { n: 'DPT_DayNight', en: 'day/night', de: 'Tag/Nacht' },
  '1.100': { n: 'DPT_Heat_Cool', en: 'cooling/heating', de: 'heizen/kühlen' },
  '2': { n: '2.xxx', en: '1-bit controlled', de: '1-Bit gesteuert' },
  '2.001': { n: 'DPT_Switch_Control', en: 'switch control', de: 'Prio. Schalten' },
  '2.002': { n: 'DPT_Bool_Control', en: 'boolean control', de: 'Boolesche Steuerung' },
  '2.003': { n: 'DPT_Enable_Control', en: 'enable control', de: 'Prio. Freigeben' },
  '2.004': { n: 'DPT_Ramp_Control', en: 'ramp control', de: 'Prio. Übergang' },
  '2.005': { n: 'DPT_Alarm_Control', en: 'alarm control', de: 'Prio. Alarm' },
  '2.006': { n: 'DPT_BinaryValue_Control', en: 'binary value control', de: 'Prio. binärer Wert' },
  '2.007': { n: 'DPT_Step_Control', en: 'step control', de: 'Prio. Schritt' },
  '2.008': { n: 'DPT_Direction1_Control', en: 'direction control 1', de: 'Richtungskontrolle 1' },
  '2.009': { n: 'DPT_Direction2_Control', en: 'direction control 2', de: 'Richtungskontrolle 2' },
  '2.010': { n: 'DPT_Start_Control', en: 'start control', de: 'Prio. Start' },
  '2.011': { n: 'DPT_State_Control', en: 'state control', de: 'Prio. Aktivität' },
  '2.012': { n: 'DPT_Invert_Control', en: 'invert control', de: 'Prio. Invers' },
  '3': { n: '3.xxx', en: '3-bit controlled', de: '3-Bit gesteuert' },
  '3.007': { n: 'DPT_Control_Dimming', en: 'dimming control', de: 'Dimmer Schritt' },
  '3.008': { n: 'DPT_Control_Blinds', en: 'blind control', de: 'Jalousie Schritt' },
  '4': { n: '4.xxx', en: 'character', de: 'Zeichensatz' },
  '4.001': { n: 'DPT_Char_ASCII', en: 'character (ASCII)', de: 'Zeichen (ASCII)' },
  '4.002': { n: 'DPT_Char_8859_1', en: 'character (ISO 8859-1)', de: 'Zeichen (ISO 8859-1)' },
  '5': { n: '5.xxx', en: '8-bit unsigned value', de: '8-Bit vorzeichenlos' },
  '5.001': { n: 'DPT_Scaling', en: 'percentage (0..100%)', de: 'Prozent (0..100%)' },
  '5.003': { n: 'DPT_Angle', en: 'angle (degrees)', de: 'Winkel (Grad)' },
  '5.004': { n: 'DPT_Percent_U8', en: 'percentage (0..255%)', de: 'Prozent (0..255%)' },
  '5.005': { n: 'DPT_DecimalFactor', en: 'ratio (0..255)', de: 'Dezimalfaktor (0..255)' },
  '5.006': { n: 'DPT_Tariff', en: 'tariff (0..255)', de: 'Tarif (0..255)' },
  '5.010': { n: 'DPT_Value_1_Ucount', en: 'counter pulses (0..255)', de: 'Zählimpulse (0..255)' },
  '5.100': { n: 'DPT_FanStage', en: 'fan stage (0..255)', de: 'Lüfterstufe (0..255)' },
  '6': { n: '6.xxx', en: '8-bit signed value', de: '8-Bit vorzeichenbehaftet' },
  '6.001': { n: 'DPT_Percent_V8', en: 'percentage (-128..127%)', de: 'Prozent (-128..127%)' },
  '6.010': { n: 'DPT_Value_1_Count', en: 'counter pulses (-128..127)', de: 'Zählimpulse (-128..127)' },
  '6.020': { n: 'DPT_Status_Mode3', en: 'status with mode', de: 'Status mit Modus' },
  '7': { n: '7.xxx', en: '2-byte unsigned value', de: '2-Byte vorzeichenlos' },
  '7.001': { n: 'DPT_Value_2_Ucount', en: 'pulses', de: 'Pulse' },
  '7.002': { n: 'DPT_TimePeriodMsec', en: 'time (ms)', de: 'Zeit (ms)' },
  '7.003': { n: 'DPT_TimePeriod10Msec', en: 'time (10 ms)', de: 'Zeit (10 ms)' },
  '7.004': { n: 'DPT_TimePeriod100Msec', en: 'time (100 ms)', de: 'Zeit (100 ms)' },
  '7.005': { n: 'DPT_TimePeriodSec', en: 'time (s)', de: 'Zeit (s)' },
  '7.006': { n: 'DPT_TimePeriodMin', en: 'time (min)', de: 'Zeit (min)' },
  '7.007': { n: 'DPT_TimePeriodHrs', en: 'time (h)', de: 'Zeit (h)' },
  '7.010': { n: 'DPT_PropDataType', en: 'property data type', de: 'Property Datentyp' },
  '7.011': { n: 'DPT_Length_mm', en: 'length (mm)', de: 'Länge (mm)' },
  '7.012': { n: 'DPT_UElCurrentmA', en: 'current (mA)', de: 'Strom (mA)' },
  '7.013': { n: 'DPT_Brightness', en: 'brightness (lux)', de: 'Helligkeit (lux)' },
  '7.600': { n: 'DPT_Absolute_Colour_Temperature', en: 'absolute colour temperature (K)', de: 'Absolute Farbtemperatur (K)' },
  '8': { n: '8.xxx', en: '2-byte signed value', de: '2-Byte vorzeichenbehaftet' },
  '8.001': { n: 'DPT_Value_2_Count', en: 'pulses difference', de: 'Pulsdifferenz' },
  '8.002': { n: 'DPT_DeltaTimeMsec', en: 'time lag (ms)', de: 'Zeitdifferenz (ms)' },
  '8.003': { n: 'DPT_DeltaTime10Msec', en: 'time lag(10 ms)', de: 'Zeitdifferenz (10 ms)' },
  '8.004': { n: 'DPT_DeltaTime100Msec', en: 'time lag (100 ms)', de: 'Zeitdifferenz (100 ms)' },
  '8.005': { n: 'DPT_DeltaTimeSec', en: 'time lag (s)', de: 'Zeitdifferenz (s)' },
  '8.006': { n: 'DPT_DeltaTimeMin', en: 'time lag (min)', de: 'Zeitdifferenz (min)' },
  '8.007': { n: 'DPT_DeltaTimeHrs', en: 'time lag (h)', de: 'Zeitdifferenz (h)' },
  '8.010': { n: 'DPT_Percent_V16', en: 'percentage difference (%)', de: 'Prozentdifferenz (%)' },
  '8.011': { n: 'DPT_Rotation_Angle', en: 'rotation angle (°)', de: 'Rotationswinkel (°)' },
  '8.012': { n: 'DPT_Length_m', en: 'length (m)', de: 'Länge (m)' },
  '9': { n: '9.xxx', en: '2-byte float value', de: '2-Byte Gleitkommawert' },
  '9.001': { n: 'DPT_Value_Temp', en: 'temperature (°C)', de: 'Temperatur (°C)' },
  '9.002': { n: 'DPT_Value_Tempd', en: 'temperature difference (K)', de: 'Temperaturdifferenz (K)' },
  '9.003': { n: 'DPT_Value_Tempa', en: 'kelvin/hour (K/h)', de: 'Kelvin/Stunde (K/h)' },
  '9.004': { n: 'DPT_Value_Lux', en: 'lux (Lux)', de: 'Lux (Lux)' },
  '9.005': { n: 'DPT_Value_Wsp', en: 'speed (m/s)', de: 'Geschwindigkeit (m/s)' },
  '9.006': { n: 'DPT_Value_Pres', en: 'pressure (Pa)', de: 'Druck (Pa)' },
  '9.007': { n: 'DPT_Value_Humidity', en: 'humidity (%)', de: 'Feuchtigkeit (%)' },
  '9.008': { n: 'DPT_Value_AirQuality', en: 'parts/million (ppm)', de: 'Teile/Million (ppm)' },
  '9.009': { n: 'DPT_Value_AirFlow', en: 'air flow (m³/h)', de: 'Luftdurchsatz (m³/h)' },
  '9.010': { n: 'DPT_Value_Time1', en: 'time (s)', de: 'Zeit (s)' },
  '9.011': { n: 'DPT_Value_Time2', en: 'time (ms)', de: 'Zeit (ms)' },
  '9.020': { n: 'DPT_Value_Volt', en: 'voltage (mV)', de: 'Spannung (mV)' },
  '9.021': { n: 'DPT_Value_Curr', en: 'current (mA)', de: 'Strom (mA)' },
  '9.022': { n: 'DPT_PowerDensity', en: 'power density (W/m²)', de: 'Leistungsdichte (W/m²)' },
  '9.023': { n: 'DPT_KelvinPerPercent', en: 'kelvin/percent (K/%)', de: 'Kelvin/Prozent (K/%)' },
  '9.024': { n: 'DPT_Power', en: 'power (kW)', de: 'Leistung (kW)' },
  '9.025': { n: 'DPT_Value_Volume_Flow', en: 'volume flow (l/h)', de: 'Durchflussmenge (l/h)' },
  '9.026': { n: 'DPT_Rain_Amount', en: 'rain amount (l/m²)', de: 'Regenmenge (l/m²)' },
  '9.027': { n: 'DPT_Value_Temp_F', en: 'temperature (°F)', de: 'Temperatur (°F)' },
  '9.028': { n: 'DPT_Value_Wsp_kmh', en: 'wind speed (km/h)', de: 'Windgeschwindigkeit (km/h)' },
  '9.029': { n: 'DPT_Value_Absolute_Humidity', en: 'absolute humidity (g/m³)', de: 'Absolute Feuchtigkeit (g/m³)' },
  '9.030': { n: 'DPT_Concentration_µgm3', en: 'concentration (µg/m³)', de: 'Dichte (µg/m³)' },
  '9.031': { n: 'DPT_Coefficient', en: 'coefficient', de: 'coefficient' },
  '10': { n: '10.xxx', en: 'time', de: 'Zeit' },
  '10.001': { n: 'DPT_TimeOfDay', en: 'time of day', de: 'Tageszeit' },
  '11': { n: '11.xxx', en: 'date', de: 'Datum' },
  '11.001': { n: 'DPT_Date', en: 'date', de: 'Datum' },
  '12': { n: '12.xxx', en: '4-byte unsigned value', de: '4-Byte vorzeichenlos' },
  '12.001': { n: 'DPT_Value_4_Ucount', en: 'counter pulses (unsigned)', de: 'Zählimpulse (vorzeichenlos)' },
  '12.100': { n: 'DPT_LongTimePeriod_Sec', en: 'counter timesec (s)', de: 'Zähler Zeit Sek (s)' },
  '12.101': { n: 'DPT_LongTimePeriod_Min', en: 'counter timemin (min)', de: 'Zähler Zeit Min (min)' },
  '12.102': { n: 'DPT_LongTimePeriod_Hrs', en: 'counter timehrs (h)', de: 'Zähler Zeit Stunden (h)' },
  '12.1200': { n: 'DPT_VolumeLiquid_Litre', en: 'volume liquid (l)', de: 'Volumen Flüssigkeit (l)' },
  '12.1201': { n: 'DPT_Volume_m³', en: 'volume (m³)', de: 'Volumen (m³)' },
  '13': { n: '13.xxx', en: '4-byte signed value', de: '4-Byte vorzeichenbehaftet' },
  '13.001': { n: 'DPT_Value_4_Count', en: 'counter pulses (signed)', de: 'Zählimpulse (vorzeichenbehaftet)' },
  '13.002': { n: 'DPT_FlowRate_m3/h', en: 'flow rate (m³/h)', de: 'Durchflussmenge (m³/h)' },
  '13.010': { n: 'DPT_ActiveEnergy', en: 'active energy (Wh)', de: 'Wirkarbeit (Wh)' },
  '13.011': { n: 'DPT_ApparentEnergy', en: 'apparent energy (VAh)', de: 'Scheinarbeit (VAh)' },
  '13.012': { n: 'DPT_ReactiveEnergy', en: 'reactive energy (VARh)', de: 'Blindarbeit (VARh)' },
  '13.013': { n: 'DPT_ActiveEnergy_kWh', en: 'active energy (kWh)', de: 'Wirkarbeit (kWh)' },
  '13.014': { n: 'DPT_ApparentEnergy_kVAh', en: 'apparent energy (kVAh)', de: 'Scheinarbeit (kVAh)' },
  '13.015': { n: 'DPT_ReactiveEnergy_kVARh', en: 'reactive energy (kVARh)', de: 'Blindarbeit (kVARh)' },
  '13.016': { n: 'DPT_ActiveEnergy_MWh', en: 'active energy (MWh)', de: 'Wirkenergie (MWh)' },
  '13.100': { n: 'DPT_LongDeltaTimeSec', en: 'time lag (s)', de: 'Zeitdifferenz (s)' },
  '13.1200': { n: 'DPT_DeltaVolumeLiquid_Litre ', en: 'delta volume liquid (l)', de: 'Delta Volumen Flüssigkeit (l)' },
  '13.1201': { n: 'DPT_DeltaVolume_m³', en: 'delta volume (m³)', de: 'Delta Volumen (m³)' },
  '14': { n: '14.xxx', en: '4-byte float value', de: '4-Byte Gleitkommawert' },
  '14.000': { n: 'DPT_Value_Acceleration', en: 'acceleration (m/s²)', de: 'Beschleunigung (m/s²)' },
  '14.001': { n: 'DPT_Value_Acceleration_Angular', en: 'angular acceleration (rad/s²)', de: 'Drehbeschleunigung (rad/s²)' },
  '14.002': { n: 'DPT_Value_Activation_Energy', en: 'activation energy (J/mol)', de: 'Molare Energie (J/mol)' },
  '14.003': { n: 'DPT_Value_Activity', en: 'radioactive activity (1/s)', de: 'Radioaktivität (1/s)' },
  '14.004': { n: 'DPT_Value_Mol', en: 'amount of substance (mol)', de: 'Stoffmenge (mol)' },
  '14.005': { n: 'DPT_Value_Amplitude', en: 'amplitude', de: 'Amplitude' },
  '14.006': { n: 'DPT_Value_AngleRad', en: 'angle (radiant)', de: 'Winkel (Radiant)' },
  '14.007': { n: 'DPT_Value_AngleDeg', en: 'angle (degree)', de: 'Winkel (Grad)' },
  '14.008': { n: 'DPT_Value_Angular_Momentum', en: 'angular momentum (Js)', de: 'Dehimpuls (Js)' },
  '14.009': { n: 'DPT_Value_Angular_Velocity', en: 'angular velocity (rad/s)', de: 'Winkelfrequenz (rad/s)' },
  '14.010': { n: 'DPT_Value_Area', en: 'area (m*m)', de: 'Fläche (m²)' },
  '14.011': { n: 'DPT_Value_Capacitance', en: 'capacitance (F)', de: 'Kapazität (F)' },
  '14.012': { n: 'DPT_Value_Charge_DensitySurface', en: 'flux density (C/m²)', de: 'Flußdichte (C/m²)' },
  '14.013': { n: 'DPT_Value_Charge_DensityVolume', en: 'charge density (C/m³)', de: 'Ladungsdichte(C/m³)' },
  '14.014': { n: 'DPT_Value_Compressibility', en: 'compressibility (m²/N)', de: 'Kompressibilität (m²/N)' },
  '14.015': { n: 'DPT_Value_Conductance', en: 'conductance (S)', de: 'Leitwert (S)' },
  '14.016': { n: 'DPT_Value_Electrical_Conductivity', en: 'conductivity  (S/m)', de: 'Leitfähigkeit (S/m)' },
  '14.017': { n: 'DPT_Value_Density', en: 'density (kg/m³)', de: 'Dichte (kg/m³)' },
  '14.018': { n: 'DPT_Value_Electric_Charge', en: 'electric charge (C)', de: 'elekt. Ladung (C)' },
  '14.019': { n: 'DPT_Value_Electric_Current', en: 'electric current (A)', de: 'elekt. Strom (A)' },
  '14.020': { n: 'DPT_Value_Electric_CurrentDensity', en: 'electric current density (A/m²)', de: 'Stromdichte (A/m²)' },
  '14.021': { n: 'DPT_Value_Electric_DipoleMoment', en: 'electric dipole moment (Cm)', de: 'elekt. Dipolmoment (Cm)' },
  '14.022': { n: 'DPT_Value_Electric_Displacement', en: 'electric displacement (C/m²)', de: 'elekt. Verschiebung (C/m²)' },
  '14.023': { n: 'DPT_Value_Electric_FieldStrength', en: 'electric field strength (V/m)', de: 'elekt. Feldstärke (V/m)' },
  '14.024': { n: 'DPT_Value_Electric_Flux', en: 'electric flux (C)', de: 'elekt. Fluss (C)' },
  '14.025': { n: 'DPT_Value_Electric_FluxDensity', en: 'electric flux density (C/m²)', de: 'elek. Flussdichte (C/m²)' },
  '14.026': { n: 'DPT_Value_Electric_Polarization', en: 'electric polarization (C/m²)', de: 'elek. Polarisierung (C/m²)' },
  '14.027': { n: 'DPT_Value_Electric_Potential', en: 'electric potential (V)', de: 'elekt. Potential (V)' },
  '14.028': { n: 'DPT_Value_Electric_PotentialDifference', en: 'electric potential difference (V)', de: 'elekt. Potentialdifferenz (V)' },
  '14.029': { n: 'DPT_Value_ElectromagneticMoment', en: 'electromagnetic moment (Am²)', de: 'elektromag. Moment (Am²)' },
  '14.030': { n: 'DPT_Value_Electromotive_Force', en: 'electromotive force (V)', de: 'elekt. Kraft (V)' },
  '14.031': { n: 'DPT_Value_Energy', en: 'energy (J)', de: 'Energie (J)' },
  '14.032': { n: 'DPT_Value_Force', en: 'force (N)', de: 'Kraft (N)' },
  '14.033': { n: 'DPT_Value_Frequency', en: 'frequency (Hz)', de: 'Frequenz (Hz)' },
  '14.034': { n: 'DPT_Value_Angular_Frequency', en: 'angular frequency (rad/s)', de: 'Winkelfrequenz (rad/s)' },
  '14.035': { n: 'DPT_Value_Heat_Capacity', en: 'heat capacity (J/K)', de: 'Wärmekapazität (J/K)' },
  '14.036': { n: 'DPT_Value_Heat_FlowRate', en: 'heat flow rate (W)', de: 'Wärmefluss (W)' },
  '14.037': { n: 'DPT_Value_Heat_Quantity', en: 'heat quantity', de: 'Wärmemenge (J)' },
  '14.038': { n: 'DPT_Value_Impedance', en: 'impedance (Ω)', de: 'Widerstand (Ω)' },
  '14.039': { n: 'DPT_Value_Length', en: 'length (m)', de: 'Länge (m)' },
  '14.040': { n: 'DPT_Value_Light_Quantity', en: 'light quantity (J)', de: 'Lichtmenge (J)' },
  '14.041': { n: 'DPT_Value_Luminance', en: 'luminance (cd/m²)', de: 'Helligkeit (cd/m²)' },
  '14.042': { n: 'DPT_Value_Luminous_Flux', en: 'luminous flux (lm)', de: 'Lichtstrom (lm)' },
  '14.043': { n: 'DPT_Value_Luminous_Intensity', en: 'luminous intensity (cd)', de: 'Leuchtstärke (cd)' },
  '14.044': { n: 'DPT_Value_Magnetic_FieldStrength', en: 'magnetic field strength (A/m)', de: 'Magnetfeldstärke (A/m))' },
  '14.045': { n: 'DPT_Value_Magnetic_Flux', en: 'magnetic flux (Wb)', de: 'Magnetischer Fluss (Wb)' },
  '14.046': { n: 'DPT_Value_Magnetic_FluxDensity', en: 'magnetic flux density (T)', de: 'Magnetische Flussdichte (T)' },
  '14.047': { n: 'DPT_Value_Magnetic_Moment', en: 'magnetic moment (Am²)', de: 'Magnetisches Moment (Am²)' },
  '14.048': { n: 'DPT_Value_Magnetic_Polarization', en: 'magnetic polarization (T)', de: 'Magnetische Polarisation (T)' },
  '14.049': { n: 'DPT_Value_Magnetization', en: 'magnetization (A/m)', de: 'Magnetisierung (A/m)' },
  '14.050': { n: 'DPT_Value_MagnetomotiveForce', en: 'magnetomotive force (A)', de: 'Magnetomotorische Kraft (A)' },
  '14.051': { n: 'DPT_Value_Mass', en: 'mass (kg)', de: 'Masse (kg)' },
  '14.052': { n: 'DPT_Value_MassFlux', en: 'mass flux (kg/s)', de: 'Massendurchatz (kg/s)' },
  '14.053': { n: 'DPT_Value_Momentum', en: 'momentum (N/s)', de: 'Moment (N/s)' },
  '14.054': { n: 'DPT_Value_Phase_AngleRad', en: 'phase angle (rad)', de: 'Phasenwinkel (rad)' },
  '14.055': { n: 'DPT_Value_Phase_AngleDeg', en: 'phase angle (°)', de: 'Phasenwinkel (°)' },
  '14.056': { n: 'DPT_Value_Power', en: 'power (W)', de: 'Leistung (W)' },
  '14.057': { n: 'DPT_Value_Power_Factor', en: 'power factor (cos Φ)', de: 'Leistungsfaktor (cos Φ) ' },
  '14.058': { n: 'DPT_Value_Pressure', en: 'pressure (Pa)', de: 'Druck (Pa)' },
  '14.059': { n: 'DPT_Value_Reactance', en: 'reactance (Ω)', de: 'Blindleitwert (Ω)' },
  '14.060': { n: 'DPT_Value_Resistance', en: 'resistance (Ω)', de: 'Widerstand (Ω)' },
  '14.061': { n: 'DPT_Value_Resistivity', en: 'resistivity (Ωm)', de: 'spez. elekt. Widerstand (Ωm)' },
  '14.062': { n: 'DPT_Value_SelfInductance', en: 'self inductance (H)', de: 'Selbstinduktivität (H)' },
  '14.063': { n: 'DPT_Value_SolidAngle', en: 'solid angle (sr)', de: 'Raumwinkel (sr)' },
  '14.064': { n: 'DPT_Value_Sound_Intensity', en: 'sound intensity (W/m²)', de: 'Lautstärke (W/m²)' },
  '14.065': { n: 'DPT_Value_Speed', en: 'speed (m/s)', de: 'Geschwindigkeit (m/s)' },
  '14.066': { n: 'DPT_Value_Stress', en: 'stress (Pa)', de: 'Belastung (Pa)' },
  '14.067': { n: 'DPT_Value_Surface_Tension', en: 'surface tension (N/m)', de: 'Oberflächenspannung (N/m)' },
  '14.068': { n: 'DPT_Value_Common_Temperature', en: 'temperature (°C)', de: 'Temperatur (°C)' },
  '14.069': { n: 'DPT_Value_Absolute_Temperature', en: 'temperature absolute (K)', de: 'Absoluttemperatur (°C)' },
  '14.070': { n: 'DPT_Value_TemperatureDifference', en: 'temperature difference (K)', de: 'Temperaturdifferenz (K)' },
  '14.071': { n: 'DPT_Value_Thermal_Capacity', en: 'thermal capacity (J/K)', de: 'Wärmekapazität (J/K)' },
  '14.072': { n: 'DPT_Value_Thermal_Conductivity', en: 'thermal conductivity (W/mK)', de: 'Wärmeleitfähigkeit (W/mK)' },
  '14.073': { n: 'DPT_Value_ThermoelectricPower', en: 'thermoelectric power (V/K)', de: 'Thermoelekrische Energie (V/K)' },
  '14.074': { n: 'DPT_Value_Time', en: 'time (s)', de: 'Zeit (s)' },
  '14.075': { n: 'DPT_Value_Torque', en: 'torque (Nm)', de: 'Drehmoment (Nm)' },
  '14.076': { n: 'DPT_Value_Volume', en: 'volume (m³)', de: 'Volumen (m³)' },
  '14.077': { n: 'DPT_Value_Volume_Flux', en: 'volume flux (m³/s)', de: 'Durchfluss (m³/s)' },
  '14.078': { n: 'DPT_Value_Weight', en: 'weight (N)', de: 'Gewicht (N)' },
  '14.079': { n: 'DPT_Value_Work', en: 'work (J)', de: 'Arbeit (J)' },
  '14.080': { n: 'DPT_Value_ApparentPower', en: 'apparent power (VA)', de: 'apparent power (VA)' },
  '14.1200': { n: 'DPT_Volume_Flux_Meter', en: 'volume flux for meters (m³/h)', de: 'Volumenstrom für Zähler (m³/h)' },
  '14.1201': { n: 'DPT_Volume_Flux_ls', en: 'volume flux for meters (1/ls)', de: 'Volumenstrom für Zähler (1/ls)' },
  '15': { n: '15.xxx', en: 'entrance access', de: 'Zugang' },
  '15.000': { n: 'DPT_Access_Data', en: 'entrance access', de: 'Zugang' },
  '16': { n: '16.xxx', en: 'character string', de: 'Zeichensatz' },
  '16.000': { n: 'DPT_String_ASCII', en: 'Character String (ASCII)', de: 'Zeichen (ASCII)' },
  '16.001': { n: 'DPT_String_8859_1', en: 'Character String (ISO 8859-1)', de: 'Zeichen (ISO 8859-1)' },
  '17': { n: '17.xxx', en: 'scene number', de: 'Szenen Nummer' },
  '17.001': { n: 'DPT_SceneNumber', en: 'scene number', de: 'Szenen Nummer' },
  '18': { n: '18.xxx', en: 'scene control', de: 'Szenensteuerung' },
  '18.001': { n: 'DPT_SceneControl', en: 'scene control', de: 'Szenensteuerung' },
  '19': { n: '19.xxx', en: 'Date Time', de: 'Datum/Zeit' },
  '19.001': { n: 'DPT_DateTime', en: 'date time', de: 'Datum/Zeit' },
  '20': { n: '20.xxx', en: '1-byte', de: '1-Byte' },
  '20.001': { n: 'DPT_SCLOMode', en: 'SCLO mode', de: 'SCLO Modus' },
  '20.002': { n: 'DPT_BuildingMode', en: 'building mode', de: 'Gebäude Modus' },
  '20.003': { n: 'DPT_OccMode', en: 'occupied', de: 'Belegung' },
  '20.004': { n: 'DPT_Priority', en: 'priority', de: 'Prioriät' },
  '20.005': { n: 'DPT_LightApplicationMode', en: 'light application mode', de: 'Licht Anwendungsmodus' },
  '20.006': { n: 'DPT_ApplicationArea', en: 'light application area', de: 'Licht Anwendungsbereich' },
  '20.007': { n: 'DPT_AlarmClassType', en: 'alarm class', de: 'Alarmklasse' },
  '20.008': { n: 'DPT_PSUMode', en: 'PSU mode', de: 'PSU Modus' },
  '20.011': { n: 'DPT_ErrorClass_System', en: 'system error class', de: 'System Fehlerklasse' },
  '20.012': { n: 'DPT_ErrorClass_HVAC', en: 'HVAC error class', de: 'HVAC Fehlerklasse' },
  '20.013': { n: 'DPT_Time_Delay', en: 'time delay', de: 'Zeitdifferenz' },
  '20.014': { n: 'DPT_Beaufort_Wind_Force_Scale', en: 'wind force scale (0..12)', de: 'Windstärke (0..12)' },
  '20.017': { n: 'DPT_SensorSelect', en: 'sensor mode', de: 'Sensor Modus' },
  '20.020': { n: 'DPT_ActuatorConnectType', en: 'actuator connect type', de: 'Aktor Verbindungstyp' },
  '20.021': { n: 'DPT_Cloud_Cover', en: 'cloud cover', de: 'Wolkendecke' },
  '20.022': { n: 'DPT_PowerReturnMode', en: 'power return mode', de: 'Modus nach Spannungswiederkehr' },
  '20.100': { n: 'DPT_FuelType', en: 'fuel type', de: 'Kraftstofftyp' },
  '20.101': { n: 'DPT_BurnerType', en: 'burner type', de: 'Brennertyp' },
  '20.102': { n: 'DPT_HVACMode', en: 'HVAC mode', de: 'HVAC Modus' },
  '20.103': { n: 'DPT_DHWMode', en: 'DHW mode', de: 'DHW Modus' },
  '20.104': { n: 'DPT_LoadPriority', en: 'load priority', de: 'Ladepriorität' },
  '20.105': { n: 'DPT_HVACContrMode', en: 'HVAC control mode', de: 'HVAC Kontrollmodus' },
  '20.106': { n: 'DPT_HVACEmergMode', en: 'HVAC emergency mode', de: 'HVAC Notfall Modus' },
  '20.107': { n: 'DPT_ChangeoverMode', en: 'changeover mode', de: 'Übergangsmodus' },
  '20.108': { n: 'DPT_ValveMode', en: 'valve mode', de: 'Ventilmodus' },
  '20.109': { n: 'DPT_DamperMode', en: 'damper mode', de: 'Klappenmodus' },
  '20.110': { n: 'DPT_HeaterMode', en: 'heater mode', de: 'Heizmodus' },
  '20.111': { n: 'DPT_FanMode', en: 'fan mode', de: 'Lüftermodus' },
  '20.112': { n: 'DPT_MasterSlaveMode', en: 'master/slave mode', de: 'Master/Slave Modus' },
  '20.113': { n: 'DPT_StatusRoomSetp', en: 'status room setpoint', de: 'Status Raum Sollwert' },
  '20.114': { n: 'DPT_Metering_DeviceType', en: 'metering device type', de: 'Zähler Gerätetyp' },
  '20.115': { n: 'DPT_HumDehumMode', en: 'hum dehum mode', de: 'Ent/Befeuchten Modus' },
  '20.116': { n: 'DPT_EnableHCStage', en: 'enable H/C stage', de: 'H / C-Stufe aktivieren' },
  '20.120': { n: 'DPT_ADAType', en: 'ADA type', de: 'ADA Typ' },
  '20.121': { n: 'DPT_BackupMode', en: 'backup mode', de: 'Backup Modus' },
  '20.122': { n: 'DPT_StartSynchronization', en: 'start syncronization type', de: 'Synchronisations- Starttyp' },
  '20.600': { n: 'DPT_Behaviour_Lock_Unlock', en: 'behavior lock/unlock', de: 'Verhalten sperren/freigeben' },
  '20.601': { n: 'DPT_Behaviour_Bus_Power_Up_Down', en: 'behavior bus power up/down', de: 'Verhalten Busversorgung Anlauf/Abfall' },
  '20.602': { n: 'DPT_DALI_Fade_Time', en: 'dali fade time', de: 'Dali Nachlaufzeit' },
  '20.603': { n: 'DPT_BlinkingMode', en: 'blink mode', de: 'Blinkmodus' },
  '20.604': { n: 'DPT_LightControlMode', en: 'light control mode', de: 'Licht Kontrollmodus' },
  '20.605': { n: 'DPT_SwitchPBModel', en: 'PB switch mode', de: 'PB SchaltModus' },
  '20.606': { n: 'DPT_PBAction', en: 'PB action mode', de: 'PB Aktionsmodus' },
  '20.607': { n: 'DPT_DimmPBModel', en: 'PB dimm mode', de: 'PB Dimmmodus' },
  '20.608': { n: 'DPT_SwitchOnMode', en: 'switch on mode', de: 'Einschaltmodus' },
  '20.609': { n: 'DPT_LoadTypeSet', en: 'load type', de: 'Lasttyp' },
  '20.610': { n: 'DPT_LoadTypeDetected', en: 'load type detection', de: 'Lasttyp Erkennung' },
  '20.611': { n: 'DPT_Converter_Test_Control', en: 'converter test control', de: 'Konverter Teststeuerung' },
  '20.612': { n: 'DPT_Converter_Control', en: 'converter control', de: 'converter control' },
  '20.613': { n: 'DPT_Converter_Data_Request', en: 'Converter Data Request', de: 'Converter Data Request' },
  '20.801': { n: 'DPT_SABExcept-Behaviour', en: 'SAB except behavior', de: 'SAB Ausnahmeverhalten' },
  '20.802': { n: 'DPT_SABBehaviour_Lock_Unlock', en: 'SAB behavior on lock/unlock', de: 'SAB Verhalten sperren/freigeben' },
  '20.803': { n: 'DPT_SSSBMode', en: 'SSSB mode', de: 'SSSB Modus' },
  '20.804': { n: 'DPT_BlindsControlMode', en: 'blinds control mode', de: 'Rolladen Kontrollmodus' },
  '20.1000': { n: 'DPT_CommMode', en: 'communication mode', de: 'Kommunikationsmodus' },
  '20.1001': { n: 'DPT_AddInfoTypes', en: 'additional information type', de: 'Typ der erweiterten Information' },
  '20.1002': { n: 'DPT_RF_ModeSelect', en: 'RF mode selection', de: 'Auswahl RF Modus' },
  '20.1003': { n: 'DPT_RF_FilterSelect', en: 'RF filter mode selection', de: 'Auswahl RF Filtermodus' },
  '20.1219': { n: 'DPT_EVSEMode_1', en: 'Control Pilot State', de: 'Control Pilot State' },
  '20.1220': { n: 'DPT_EVSEMode_2', en: 'OCPP State', de: 'OCPP State' },
  '20.1221': { n: 'DPT_EVSEMode_3', en: 'EVSEErrorCode', de: 'EVSEErrorCode' },
  '21': { n: '21.xxx', en: '8-bit set', de: '8-Bit Feld' },
  '21.001': { n: 'DPT_StatusGen', en: 'general status', de: 'Allgemeiner Status' },
  '21.002': { n: 'DPT_Device_Control', en: 'device control', de: 'Geräte- Kontrolle' },
  '21.100': { n: 'DPT_ForceSign', en: 'forcing signal', de: 'Zwangsführung' },
  '21.101': { n: 'DPT_ForceSignCool', en: 'forcing signal cool', de: 'Zwangsführung Cool' },
  '21.102': { n: 'DPT_StatusRHC', en: 'room heating controller status', de: 'Raumheizungsregler Status' },
  '21.103': { n: 'DPT_StatusSDHWC', en: 'solar DHW controller status', de: 'Solar DHW Regler Status' },
  '21.104': { n: 'DPT_FuelTypeSet', en: 'fuel type set', de: 'Brennstoff- Typ' },
  '21.105': { n: 'DPT_StatusRCC', en: 'room cooling controller status', de: 'Raumkühlungsregler Status' },
  '21.106': { n: 'DPT_StatusAHU', en: 'ventilation controller status', de: 'Lüftungsregler Status' },
  '21.107': { n: 'DPT_CombinedStatus_RTSM', en: 'combined status RTSM', de: 'kombinierter Status RTSM' },
  '21.601': { n: 'DPT_LightActuatorErrorInfo', en: 'lighting actuator error information', de: 'Licht Aktor Fehler Information' },
  '21.1000': { n: 'DPT_RF_ModeInfo', en: 'RF communication mode info', de: 'RF- Kommunikationsmodus Info' },
  '21.1001': { n: 'DPT_RF_FilterInfo', en: 'cEMI server supported RF filtering modes', de: 'cEMI Server unterstützte RF Filter Modi' },
  '21.1010': { n: 'DPT_Channel_Activation_8', en: 'channel activation for 8 channels', de: 'Kanalaktivierung für 8 Kanäle' },
  '22': { n: '22.xxx', en: '16-bit set', de: '16-Bit Feld' },
  '22.100': { n: 'DPT_StatusDHWC', en: 'DHW controller status', de: 'DHW Regler Status' },
  '22.101': { n: 'DPT_StatusRHCC', en: 'RHCC status', de: 'RHCC Status' },
  '22.102': { n: 'DPT_CombinedStatus_HVA', en: 'combined status HVA', de: 'HVA kombinierter Status' },
  '22.103': { n: 'DPT_CombinedStatus_RTC', en: 'combined status RTC', de: 'RTC kombinierter Status' },
  '22.1000': { n: 'DPT_Media', en: 'media', de: 'Medium' },
  '22.1010': { n: 'DPT_Channel_Activation_16', en: 'channel activation for 16 channels', de: 'Kanalaktivierung für 16 Kanäle' },
  '23': { n: '23.xxx', en: '2-bit set', de: '2-Bit Feld' },
  '23.001': { n: 'DPT_OnOffAction', en: 'on/off action', de: 'Ein/Aus Aktion' },
  '23.002': { n: 'DPT_Alarm_Reaction', en: 'alarm reaction', de: 'Alarm Reaktion' },
  '23.003': { n: 'DPT_UpDown_Action', en: 'up/down action', de: 'Auf/Ab Aktion' },
  '23.102': { n: 'DPT_HVAC_PB_Action', en: 'HVAC push button action', de: 'HVAC Taster Aktion' },
  '24': { n: '24.xxx', en: '', de: '' },
  '24.001': { n: 'DPT_VarString_8859_1', en: 'Variable-Length ISO-8859-1 String', de: 'Variable-Length ISO-8859-1 String' },
  '25': { n: '25.xxx', en: '2-nibble set', de: '2-Nibble Feld' },
  '25.1000': { n: 'DPT_DoubleNibble', en: 'busy/nak repetitions', de: 'Busy/Nak Wiederholungen' },
  '26': { n: '26.xxx', en: '8-bit set', de: '8-Bit Feld' },
  '26.001': { n: 'DPT_SceneInfo', en: 'scene information', de: 'Szeneninformation' },
  '27': { n: '27.xxx', en: '32-bit set', de: '32-Bit Feld' },
  '27.001': { n: 'DPT_CombinedInfoOnOff', en: 'bit-combined info on/off', de: 'Bit-kombinierte Info Ein/Aus' },
  '28': { n: '28.xxx', en: '', de: '' },
  '28.001': { n: 'DPT_UTF-8', en: 'Unicode UTF-8 String', de: 'Unicode UTF-8 String' },
  '29': { n: '29.xxx', en: 'electrical energy', de: 'Elektrische Energie' },
  '29.010': { n: 'DPT_ActiveEnergy_V64', en: 'active energy (Wh)', de: 'Wirkarbeit (Wh)' },
  '29.011': { n: 'DPT_ApparentEnergy_V64', en: 'apparent energy (VAh)', de: 'Scheinarbeit (VAh)' },
  '29.012': { n: 'DPT_ReactiveEnergy_V64', en: 'reactive energy (VARh)', de: 'Blindarbeit (VARh)' },
  '30': { n: '30.xxx', en: '24 times channel activation', de: '24- fach Kanalaktivierung' },
  '30.1010': { n: 'DPT_Channel_Activation_24', en: 'activation state 0..23', de: 'Aktivierungsstatus 0..23' },
  '206': { n: '206.xxx', en: '16-bit unsigned value & 8-bit enum', de: '16-Bit vorzeichenlos und 8-Bit Auswahl' },
  '206.100': { n: 'DPT_HVACModeNext', en: 'time delay & HVAC mode', de: 'Zeitverzögerung und HVAC Modus' },
  '206.102': { n: 'DPT_DHWModeNext', en: 'time delay & DHW mode', de: 'Zeitverzögerung und DHW Modus' },
  '206.104': { n: 'DPT_OccModeNext', en: 'time delay & occupancy mode', de: 'Zeitverzögerung und Belegungsmodus' },
  '206.105': { n: 'DPT_BuildingModeNext', en: 'time delay & building mode', de: 'Zeitverzögerung und Gebäudemodus' },
  '207': { n: '207.xxx', en: '8-bit unsigned value & 8-bit enum', de: '8-bit unsigned value & 8-bit enum' },
  '207.600': { n: 'DPT_StatusLightingActuator', en: 'Status Lighting Actuator', de: 'Status Lighting Actuator' },
  '217': { n: '217.xxx', en: 'datapoint type version', de: 'Datenpunkttyp Version' },
  '217.001': { n: 'DPT_Version', en: 'DPT version', de: 'DPT Version' },
  '219': { n: '219.xxx', en: 'alarm info', de: 'Alarm Info' },
  '219.001': { n: 'DPT_AlarmInfo', en: 'alarm info', de: 'Alarm Info' },
  '222': { n: '222.xxx', en: '3x 2-byte float value', de: '3x 2-Byte Gleitkommawert' },
  '222.100': { n: 'DPT_TempRoomSetpSetF16[3]', en: 'room temperature setpoint', de: 'Raumtemperatur Sollwert' },
  '222.101': { n: 'DPT_TempRoomSetpSetShiftF16[3]', en: 'room temperature setpoint shift', de: 'Raumtemperatur Sollwertverschiebung' },
  '225': { n: '225.xxx', en: 'scaling speed', de: 'scaling speed' },
  '225.001': { n: 'Scaling Speed', en: 'scaling speed', de: 'Skaliergeschwindigkeit' },
  '225.002': { n: 'Scaling step time', en: 'scaling step time', de: 'Skalierung Schrittzeit' },
  '229': { n: '229.xxx', en: '4-1-1 byte combined information', de: '4-1-1 Byte kombinierte Information' },
  '229.001': { n: 'DPT_MeteringValue', en: 'metering value (value,encoding,cmd)', de: 'Ablesewert (Wert,Encoding,Befehl)' },
  '230': { n: '230.xxx', en: 'MBus address', de: 'MBus Adresse' },
  '230.1000': { n: 'DPT_MBus_Address', en: 'MBus address', de: 'MBus Adresse' },
  '232': { n: '232.xxx', en: '3-byte colour RGB', de: '3-Byte Farbe RGB' },
  '232.600': { n: 'DPT_Colour_RGB', en: 'RGB value 3x(0..255)', de: 'RGB Wert 3x(0..255)' },
  '232.601': { n: 'DPT_Colour_HSV', en: 'Colour HSV', de: 'Farbe HSV' },
  '234': { n: '234.xxx', en: 'language code ISO 639-1', de: 'Sprachcode ISO 639-1' },
  '234.001': { n: 'DPT_LanguageCodeAlpha2_ASCII', en: 'language code (ASCII)', de: 'Sprachcode (ASCII)' },
  '235': { n: '235.xxx', en: 'Signed value with classification and validity', de: 'Vorzeichenbehaftet mit Klassifizierung und Gültigkeit' },
  '235.001': { n: 'DPT_Tariff_ActiveEnergy', en: 'electrical energy with tariff', de: 'elektrische Energie mit Tarif' },
  '236': { n: '236.xxx', en: 'Prioritised Mode Control', de: 'Priorisierte Modussteuerung' },
  '236.001': { n: 'DPT_Prioritised_Mode_Control', en: 'priority control', de: 'Priorisierte Modussteuerung' },
  '237': { n: '237.xxx', en: 'configuration/ diagnostics', de: 'Konfiguration/ Diagnose' },
  '237.600': { n: 'DPT_DALI_Control_Gear_Diagnostic', en: 'diagnostic value', de: 'Diagnosewert' },
  '238': { n: '238.xxx', en: 'configuration/ diagnostics', de: 'Konfiguration/ Diagnose' },
  '238.600': { n: 'DPT_DALI_Diagnostics', en: 'diagnostic value', de: 'Diagnosewert' },
  '240': { n: '240.xxx', en: 'positions', de: 'Positionen' },
  '240.800': { n: 'DPT_CombinedPosition', en: 'combined position', de: 'Kombinierte Position' },
  '241': { n: '241.xxx', en: 'status', de: 'Status' },
  '241.800': { n: 'DPT_StatusSAB', en: 'status sunblind & shutter actuator', de: 'Status Beschattung & Jalousieaktoren' },
  '242': { n: '242.xxx', en: 'status', de: 'Status' },
  '242.600': { n: 'DPT_Colour_xyY', en: 'colour xyY', de: 'Farbe xyY' },
  '244': { n: '244.xxx', en: 'Converter Status', de: 'Konverter Status' },
  '244.600': { n: 'DPT_Converter_Status', en: 'DALI converter status', de: 'DALI Konverter Status' },
  '245': { n: '245.xxx', en: 'Converter test result', de: 'Konverter Testergebnis' },
  '245.600': { n: 'DPT_Converter_Test_Result', en: 'DALI converter test result', de: 'DALI Konverter Testergebnis' },
  '246': { n: '246.xxx', en: 'Battery Information', de: 'Batterieinformationen' },
  '246.600': { n: 'DPT_Battery_Info', en: 'Battery Information', de: 'Batterieinformationen' },
  '247': { n: '247.xxx', en: 'Converter Test Info', de: 'Converter Test Info' },
  '247.600': { n: 'DPT_Converter_Test_Info', en: 'Converter Test Info', de: 'Converter Test Info' },
  '248': { n: '248.xxx', en: 'DPT_Converter_Info_Fix', de: 'DPT_Converter_Info_Fix' },
  '248.600': { n: 'DPT_Converter_Info_Fix', en: 'Converter Info Fix', de: 'Converter Info Fix' },
  '249': { n: '249.xxx', en: 'brightness colour temperature transition', de: 'brightness colour temperature transition' },
  '249.600': { n: 'DPT_Brightness_Colour_Temperature_Transition', en: 'brightness colour temperature transition', de: 'Helligkeit Farbtemperaturübergang' },
  '250': { n: '250.xxx', en: 'status', de: 'Status' },
  '250.600': { n: 'DPT_Brightness_Colour_Temperature_Control', en: 'brightness colour temperature control', de: 'Helligkeit Farbtemperaturregelung' },
  '251': { n: '251.xxx', en: 'Colour RGBW', de: '4-Byte Farbe RGBW' },
  '251.600': { n: 'DPT_Colour_RGBW', en: 'RGBW value 4x(0..100%)', de: 'RGBW Wert 4x(0..100%)' },
  '251.601': { n: 'DPT_Colour_HSVW', en: 'Colour HSVW', de: 'Farbe HSVW' },
  '252': { n: '252.xxx', en: 'Relative Control RGBW', de: 'Relative Control RGBW' },
  '252.600': { n: 'DPT_Relative_Control_RGBW', en: 'RGBW relative control', de: 'RGBW relative control' },
  '252.601': { n: 'DPT_Relative_Control_HSVW', en: 'HSVW relative control', de: 'HSVW relative control' },
  '254': { n: '254.xxx', en: 'Relative Control RGB', de: 'Relative Control RGB' },
  '254.600': { n: 'DPT_Relative_Control_RGB', en: 'RGB relative control', de: 'RGB relative control' },
  '254.601': { n: 'DPT_Relative_Control_HSV', en: 'Relative Control HSV', de: 'Relative Control HSV' },
  '255': { n: '255.xxx', en: 'F32F32', de: 'F32F32' },
  '255.001': { n: 'DPT_GeographicalLocation', en: 'geographical location (longitude and latitude) expressed in degrees', de: 'Geografischer Standort (Längen- und Breitengrad) in Grad' },
  '272': { n: '272.xxx', en: 'Converter Info', de: 'Converter Info' },
  '272.600': { n: 'DPT_Converter_Info', en: 'Converter Info', de: 'Converter Info' },
  '273': { n: '273.xxx', en: 'Forecasts for F16 values', de: 'Prognosen für F16-Werte' },
  '273.001': { n: 'DPT_Forecast_Temperature', en: 'Forecast Temperature', de: 'Vorhergesagte Temperatur' },
  '273.002': { n: 'DPT_Forecast_WindSpeed', en: 'Forecast WindSpeed', de: 'Vorhergesagte Windgeschwindigkeit' },
  '273.003': { n: 'DPT_Forecast_RelativeHumidity', en: 'Forecast RelativeHumidity', de: 'Vorhergesagte relative Luftfeuchtigkeit' },
  '273.004': { n: 'DPT_Forecast_AbsoluteHumidity', en: 'Forecast AbsoluteHumidity', de: 'Vorhergesagte absolute Luftfeuchtigkeit' },
  '273.005': { n: 'DPT_Forecast_CO2', en: 'Forecast CO2', de: 'Vorhergesagter CO2-Gehalt' },
  '273.006': { n: 'DPT_Forecast_AirPollutants', en: 'Forecast AirPollutants', de: 'Vorhergesagte Luftschadstoffe' },
  '273.007': { n: 'DPT_Forecast_SunIntensity', en: 'Forecast SunIntensity', de: 'Vorhergesagte Sonneneinstrahlung' },
  '275': { n: '275.xxx', en: 'F16F16F16F16', de: 'F16F16F16F16' },
  '275.100': { n: 'DPT_TempRoomSetpSetF16[4]', en: 'Temperature setpoint setting for 4 HVAC Modes', de: 'Temperatur Soll-Wert-Einstellung für 4 HLK Modi' },
  '275.101': { n: 'DPT_TempRoomSetpSetShiftF16[4]', en: 'Temperature setpoint shift setting for 4 HVAC Modes', de: 'Temperatur Sollwertverschiebungseinstellung für 4 HLK Modi' },
  '285': { n: '285.xxx', en: 'ipv6', de: 'ipv6' },
  '285.001': { n: 'DPT_ipv6', en: 'IPv6 address encoded in the network byte order', de: 'IPv6-Adresse kodiert in der Netzwerk-Byte-Reihenfolge' },
  '288': { n: '288.xxx', en: 'Brightness Colour RGBW Transition', de: 'Helligkeit Farbe RGBW-Übergang' },
  '288.600': { n: 'DPT_Brightness_Colour_RGBW_Transition', en: 'Brightness Colour RGBW Transition', de: 'Helligkeit/Farbe RGBW-Übergang' },
  '288.601': { n: 'DPT_Brightness_Colour_HSVW_Transition', en: 'Brightness Colour HSVW Transition', de: 'Helligkeit/Farbe HSVW-Übergang' },
};
